2022-03-31 05:12:39 | DEBUG | osdt initialized, invoked by: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tester.py '--log' | toolbox.py:359
2022-03-31 05:12:39 | INFO  | final format | toolbox.py:360
2022-03-31 05:12:39 | INFO  | toggling user data: False | user.py:581
2022-03-31 05:12:39 | INFO  | removing: C:\Users\17074\AppData\Local\osdt\osdt\osdt_workspace | user.py:590
2022-03-31 05:12:39 | INFO  | removing: D:\osdt_dev\osdt_home | user.py:590
2022-03-31 05:12:39 | INFO  | removing: C:\Users\17074\GitHub\osdt_documentation | user.py:590
2022-03-31 05:12:39 | INFO  | removing: D:\osdt_dev\test_path | user.py:590
2022-03-31 05:12:39 | INFO  | test root: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing | tester.py:157
2022-03-31 05:12:39 | INFO  | changing output path: D:\osdt_dev\osdt_home\osdt_output\_operations\python -> D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files | arguments.py:55
2022-03-31 05:12:39 | DEBUG | log file updated: D:\osdt_dev\osdt_home\osdt_output\_operations\python\osdt_log.txt -> D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\osdt_log.txt | arguments.py:49
INFO  | test | tester.py:169
INFO  | 

################################################################################
Test Log
################################################################################

 | tester.py:148
INFO  | toggling user data: False | user.py:581
INFO  | created new system: ball <osdt.system.System object at 0x000002137FF47100> | system.py:117
INFO  | system added to environment: ball <osdt.system.System object at 0x000002137FF47100> | environment.py:76
INFO  | created new system: ball <osdt.system.System object at 0x000002137FF47EE0> | system.py:117
WARN  | duplicate id found - updating original id to include index: ball -> ball_1 (<osdt.system.System object at 0x000002137FF47100>) | environment.py:226
WARN  | updating duplicate system id: ball -> ball_2 (<osdt.system.System object at 0x000002137FF47EE0>) | environment.py:233
INFO  | system added to environment: ball_2 <osdt.system.System object at 0x000002137FF47EE0> | environment.py:76
INFO  | testing: environment_tests | tester.py:90
INFO  | created new system: ball <osdt.system.System object at 0x000002137FF41790> | system.py:117
INFO  | system added to environment: ball <osdt.system.System object at 0x000002137FF41790> | environment.py:76
INFO  | created new system: ball <osdt.system.System object at 0x000002137FF88400> | system.py:117
WARN  | duplicate id found - updating original id to include index: ball -> ball_1 (<osdt.system.System object at 0x000002137FF41790>) | environment.py:226
WARN  | updating duplicate system id: ball -> ball_2 (<osdt.system.System object at 0x000002137FF88400>) | environment.py:233
INFO  | system added to environment: ball_2 <osdt.system.System object at 0x000002137FF88400> | environment.py:76
INFO  | test_add_duplicates (environment_tests.SystemTests) ... ok | tester.py:73
INFO  | created new system: ball <osdt.system.System object at 0x000002137FF889D0> | system.py:117
INFO  | created new system: ball <osdt.system.System object at 0x000002137FF88F40> | system.py:117
INFO  | system added to environment: ball <osdt.system.System object at 0x000002137FF889D0> | environment.py:76
WARN  | duplicate id found - updating original id to include index: ball -> ball_1 (<osdt.system.System object at 0x000002137FF889D0>) | environment.py:226
WARN  | updating duplicate system id: ball -> ball_2 (<osdt.system.System object at 0x000002137FF88F40>) | environment.py:233
INFO  | system added to environment: ball_2 <osdt.system.System object at 0x000002137FF88F40> | environment.py:76
INFO  | test_add_systems (environment_tests.SystemTests) ... ok | tester.py:73
INFO  | created new system: ball <osdt.system.System object at 0x000002137FF8D550> | system.py:117
INFO  | system added to environment: ball <osdt.system.System object at 0x000002137FF8D550> | environment.py:76
INFO  | created new system: ball <osdt.system.System object at 0x000002137FF8DA90> | system.py:117
WARN  | duplicate id found - updating original id to include index: ball -> ball_1 (<osdt.system.System object at 0x000002137FF8D550>) | environment.py:226
WARN  | updating duplicate system id: ball -> ball_2 (<osdt.system.System object at 0x000002137FF8DA90>) | environment.py:233
INFO  | system added to environment: ball_2 <osdt.system.System object at 0x000002137FF8DA90> | environment.py:76
INFO  | test_auto_add_systems (environment_tests.SystemTests) ... ok | tester.py:73
INFO  | ---------------------------------------------------------------------- | tester.py:73
INFO  | Ran 3 tests in 0.006s | tester.py:73
INFO  | OK | tester.py:73
INFO  | testing: fileio_tests | tester.py:90
INFO  | system added to environment: ball_1 <osdt.system.System object at 0x000002137FF47100> | environment.py:76
INFO  | exported object to yaml: GeneralConfiguration -> D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\config.yaml | fileio.py:235
INFO  | exported configuration to D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files/saved_env\config.yaml | fileio.py:77
INFO  | saved object to file: <osdt.system.System object at 0x000002137FF47100> -> D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\sys_ball_1.odst | fileio.py:60
INFO  | exported object to yaml: dict -> D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\environment.yaml | fileio.py:235
INFO  | test_save_env (fileio_tests.SaveTests) ... ok | tester.py:73
INFO  | saved object to file: <osdt.system.System object at 0x000002137FF47100> -> D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_obj.odst | fileio.py:60
INFO  | test_save_obj (fileio_tests.SaveTests) ... ok | tester.py:73
INFO  | loaded object from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\sys_ball_1.odst -> <osdt.system.System object at 0x000002137FF8DD90> | fileio.py:169
INFO  | system added to environment: ball_1 <osdt.system.System object at 0x000002137FF8DD90> | environment.py:76
INFO  | loaded environment system: ball_1 <osdt.system.System object at 0x000002137FF8DD90> | environment.py:362
INFO  | loading configuration: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\config.yaml | fileio.py:188
INFO  | environment loaded successfully from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env -> <osdt.environment.Environment object at 0x000002137FF8DD00> | fileio.py:123
INFO  | test_load_env (fileio_tests.LoadTests) ... ok | tester.py:73
INFO  | loaded object from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_obj.odst -> <osdt.system.System object at 0x000002137FEEB520> | fileio.py:169
WARN  | duplicate id found - updating original id to include index: ball_1 -> ball_1_1 (<osdt.system.System object at 0x000002137FF8DD90>) | environment.py:226
WARN  | updating duplicate system id: ball_1 -> ball_1_2 (<osdt.system.System object at 0x000002137FEEB520>) | environment.py:233
INFO  | system added to environment: ball_1_2 <osdt.system.System object at 0x000002137FEEB520> | environment.py:76
INFO  | test_load_obj (fileio_tests.LoadTests) ... ok | tester.py:73
INFO  | loaded object from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\sys_ball_1.odst -> <osdt.system.System object at 0x000002137FF93DF0> | fileio.py:169
INFO  | system added to environment: ball_1 <osdt.system.System object at 0x000002137FF93DF0> | environment.py:76
INFO  | loaded environment system: ball_1 <osdt.system.System object at 0x000002137FF93DF0> | environment.py:362
INFO  | loading configuration: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\config.yaml | fileio.py:188
INFO  | environment loaded successfully from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env -> <osdt.environment.Environment object at 0x000002137FF41790> | fileio.py:123
INFO  | test_load_env (fileio_tests.LoadTestsBad) ... FAIL | tester.py:73
INFO  | loaded object from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_obj.odst -> <osdt.system.System object at 0x000002137FF88E20> | fileio.py:169
WARN  | duplicate id found - updating original id to include index: ball_1 -> ball_1_1 (<osdt.system.System object at 0x000002137FF93DF0>) | environment.py:226
WARN  | updating duplicate system id: ball_1 -> ball_1_2 (<osdt.system.System object at 0x000002137FF88E20>) | environment.py:233
INFO  | system added to environment: ball_1_2 <osdt.system.System object at 0x000002137FF88E20> | environment.py:76
INFO  | test_load_obj (fileio_tests.LoadTestsBad) ... FAIL | tester.py:73
INFO  | ====================================================================== | tester.py:73
INFO  | FAIL: test_load_env (fileio_tests.LoadTestsBad) | tester.py:73
INFO  | ---------------------------------------------------------------------- | tester.py:73
INFO  | Traceback (most recent call last):
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fileio_tests.py", line 65, in test_load_env
    self.compare_states(ball_state2, sys1.x())
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fileio_tests.py", line 53, in compare_states
    self.assertEqual(orig.__dict__[key], loaded.__dict__[key])
AssertionError: 999.99 != 1.0 | tester.py:73
INFO  | ====================================================================== | tester.py:73
INFO  | FAIL: test_load_obj (fileio_tests.LoadTestsBad) | tester.py:73
INFO  | ---------------------------------------------------------------------- | tester.py:73
INFO  | Traceback (most recent call last):
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fileio_tests.py", line 59, in test_load_obj
    self.compare_states(orig,loaded)
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fileio_tests.py", line 53, in compare_states
    self.assertEqual(orig.__dict__[key], loaded.__dict__[key])
AssertionError: 43243.0 != 1.0 | tester.py:73
INFO  | ---------------------------------------------------------------------- | tester.py:73
INFO  | Ran 6 tests in 0.042s | tester.py:73
INFO  | FAILED (failures=2) | tester.py:73
INFO  | testing: fio2 | tester.py:90
INFO  | system added to environment: ball_2 <osdt.system.System object at 0x000002137FF47EE0> | environment.py:76
INFO  | exported object to yaml: GeneralConfiguration -> D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\config.yaml | fileio.py:235
INFO  | exported configuration to D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files/saved_env\config.yaml | fileio.py:77
INFO  | saved object to file: <osdt.system.System object at 0x000002137FF47EE0> -> D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\sys_ball_2.odst | fileio.py:60
INFO  | exported object to yaml: dict -> D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\environment.yaml | fileio.py:235
INFO  | test_save_env (fio2.SaveTests) ... ok | tester.py:73
INFO  | saved object to file: <osdt.system.System object at 0x000002137FF47EE0> -> D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_obj.odst | fileio.py:60
INFO  | test_save_obj (fio2.SaveTests) ... ok | tester.py:73
INFO  | loaded object from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\sys_ball_2.odst -> <osdt.system.System object at 0x000002137FF8D3D0> | fileio.py:169
INFO  | system added to environment: ball_2 <osdt.system.System object at 0x000002137FF8D3D0> | environment.py:76
INFO  | loaded environment system: ball_2 <osdt.system.System object at 0x000002137FF8D3D0> | environment.py:362
INFO  | loading configuration: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\config.yaml | fileio.py:188
INFO  | environment loaded successfully from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env -> <osdt.environment.Environment object at 0x000002137FF8D340> | fileio.py:123
INFO  | test_load_env (fio2.LoadTests) ... ok | tester.py:73
INFO  | loaded object from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_obj.odst -> <osdt.system.System object at 0x000002137FFA84C0> | fileio.py:169
WARN  | duplicate id found - updating original id to include index: ball_2 -> ball_2_1 (<osdt.system.System object at 0x000002137FF8D3D0>) | environment.py:226
WARN  | updating duplicate system id: ball_2 -> ball_2_2 (<osdt.system.System object at 0x000002137FFA84C0>) | environment.py:233
INFO  | system added to environment: ball_2_2 <osdt.system.System object at 0x000002137FFA84C0> | environment.py:76
INFO  | test_load_obj (fio2.LoadTests) ... ok | tester.py:73
INFO  | loaded object from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\sys_ball_2.odst -> <osdt.system.System object at 0x000002137FFA8C10> | fileio.py:169
INFO  | system added to environment: ball_2 <osdt.system.System object at 0x000002137FFA8C10> | environment.py:76
INFO  | loaded environment system: ball_2 <osdt.system.System object at 0x000002137FFA8C10> | environment.py:362
INFO  | loading configuration: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env\config.yaml | fileio.py:188
INFO  | environment loaded successfully from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_env -> <osdt.environment.Environment object at 0x000002137FFA8A30> | fileio.py:123
INFO  | test_load_env (fio2.LoadTestsBad) ... FAIL | tester.py:73
INFO  | loaded object from file: D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\files\files\saved_obj.odst -> <osdt.system.System object at 0x000002137FF1DE50> | fileio.py:169
WARN  | duplicate id found - updating original id to include index: ball_2 -> ball_2_1 (<osdt.system.System object at 0x000002137FFA8C10>) | environment.py:226
WARN  | updating duplicate system id: ball_2 -> ball_2_2 (<osdt.system.System object at 0x000002137FF1DE50>) | environment.py:233
INFO  | system added to environment: ball_2_2 <osdt.system.System object at 0x000002137FF1DE50> | environment.py:76
INFO  | test_load_obj (fio2.LoadTestsBad) ... FAIL | tester.py:73
INFO  | ====================================================================== | tester.py:73
INFO  | FAIL: test_load_env (fio2.LoadTestsBad) | tester.py:73
INFO  | ---------------------------------------------------------------------- | tester.py:73
INFO  | Traceback (most recent call last):
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fio2.py", line 65, in test_load_env
    self.compare_states(ball_state2, sys1.x())
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fio2.py", line 53, in compare_states
    self.assertEqual(orig.__dict__[key], loaded.__dict__[key])
AssertionError: 999.99 != 1.0 | tester.py:73
INFO  | ====================================================================== | tester.py:73
INFO  | FAIL: test_load_obj (fio2.LoadTestsBad) | tester.py:73
INFO  | ---------------------------------------------------------------------- | tester.py:73
INFO  | Traceback (most recent call last):
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fio2.py", line 59, in test_load_obj
    self.compare_states(orig,loaded)
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fio2.py", line 53, in compare_states
    self.assertEqual(orig.__dict__[key], loaded.__dict__[key])
AssertionError: 43243.0 != 1.0 | tester.py:73
INFO  | ---------------------------------------------------------------------- | tester.py:73
INFO  | Ran 6 tests in 0.038s | tester.py:73
INFO  | FAILED (failures=2) | tester.py:73
INFO  | unit testing complete:

################################################################################
environment_tests
################################################################################

test_add_duplicates (environment_tests.SystemTests) ... ok
test_add_systems (environment_tests.SystemTests) ... ok
test_auto_add_systems (environment_tests.SystemTests) ... ok

----------------------------------------------------------------------
Ran 3 tests in 0.006s

OK

################################################################################
fileio_tests
################################################################################

test_save_env (fileio_tests.SaveTests) ... ok
test_save_obj (fileio_tests.SaveTests) ... ok
test_load_env (fileio_tests.LoadTests) ... ok
test_load_obj (fileio_tests.LoadTests) ... ok
test_load_env (fileio_tests.LoadTestsBad) ... FAIL
test_load_obj (fileio_tests.LoadTestsBad) ... FAIL

======================================================================
FAIL: test_load_env (fileio_tests.LoadTestsBad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fileio_tests.py", line 65, in test_load_env
    self.compare_states(ball_state2, sys1.x())
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fileio_tests.py", line 53, in compare_states
    self.assertEqual(orig.__dict__[key], loaded.__dict__[key])
AssertionError: 999.99 != 1.0

======================================================================
FAIL: test_load_obj (fileio_tests.LoadTestsBad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fileio_tests.py", line 59, in test_load_obj
    self.compare_states(orig,loaded)
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fileio_tests.py", line 53, in compare_states
    self.assertEqual(orig.__dict__[key], loaded.__dict__[key])
AssertionError: 43243.0 != 1.0

----------------------------------------------------------------------
Ran 6 tests in 0.042s

FAILED (failures=2)

################################################################################
fio2
################################################################################

test_save_env (fio2.SaveTests) ... ok
test_save_obj (fio2.SaveTests) ... ok
test_load_env (fio2.LoadTests) ... ok
test_load_obj (fio2.LoadTests) ... ok
test_load_env (fio2.LoadTestsBad) ... FAIL
test_load_obj (fio2.LoadTestsBad) ... FAIL

======================================================================
FAIL: test_load_env (fio2.LoadTestsBad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fio2.py", line 65, in test_load_env
    self.compare_states(ball_state2, sys1.x())
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fio2.py", line 53, in compare_states
    self.assertEqual(orig.__dict__[key], loaded.__dict__[key])
AssertionError: 999.99 != 1.0

======================================================================
FAIL: test_load_obj (fio2.LoadTestsBad)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fio2.py", line 59, in test_load_obj
    self.compare_states(orig,loaded)
  File "D:\osdt_dev\osdt_home\osdt_examples\osdt_testing\tests\fio2.py", line 53, in compare_states
    self.assertEqual(orig.__dict__[key], loaded.__dict__[key])
AssertionError: 43243.0 != 1.0

----------------------------------------------------------------------
Ran 6 tests in 0.038s

FAILED (failures=2)
 | tester.py:152
